### PR TITLE
Added tracking of system URIs incase the URI cannot be built based on Ids

### LINKED ISSUE #29: power_control.py throws AttributeError: 'RestResponse' object has no attribute 'is_processing'
```
$ python3 Redfish-Usecase-Checkers/power_control/power_control.py -r xx.xx.xx.xx -u root -p 0penBmc -S Always
Found 1 system instances
Resetting 1318ECA using On
Traceback (most recent call last):
  File "Redfish-Usecase-Checkers/power_control/power_control.py", line 79, in <module>
    response = redfish_utilities.poll_task_monitor( redfish_obj, response )
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/redfish_utilities/tasks.py", line 32, in poll_task_monitor
    if not response.is_processing:
AttributeError: 'RestResponse' object has no attribute 'is_processing'
```

```
$ python -V
Python 3.6.3

$ pip3 list | grep -e redfish -e jsonschema
jsonschema                      2.6.0
redfish                         2.0.7
redfish-utilities               1.0.1
redfishtool                     1.0.8
````

### PR DESCRIPTION
**Pull request by mraineri**
Also added checking if the PowerState property is present before trying to use it.

Fix #29

### CODE REVIEW

**Comment by gkeishin** [comment]
```
$ git  clone -b Power-Control-Error-Handling https://github.com/DMTF/Redfish-Usecase-Checkers
Cloning into 'Redfish-Usecase-Checkers'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 274 (delta 0), reused 2 (delta 0), pack-reused 270
Receiving objects: 100% (274/274), 71.39 KiB | 0 bytes/s, done.
Resolving deltas: 100% (140/140), done.
```

```
gkeishin@ ~/DMTF/Redfish-Usecase-Checkers
$ git branch
* Power-Control-Error-Handling
```

```
$ python3 Redfish-Usecase-Checkers/power_control/power_control.py -r xx.xx.xx.xx -u root -p 0penBmc -S Always
Found 1 system instances
Resetting WITHERSPOON_0006 using On
Resetting WITHERSPOON_0006 using ForceOff
Resetting WITHERSPOON_0006 using ForceOn
Resetting WITHERSPOON_0006 using ForceRestart
Resetting WITHERSPOON_0006 using GracefulRestart
Resetting WITHERSPOON_0006 using GracefulShutdown
Resetting WITHERSPOON_0006 using PowerCycle
Resetting WITHERSPOON_0006 using Nmi
```

Thanks @mraineri for the fix. The changes works like charm. Apprciated

**Comment by mraineri** [comment]
Thanks for verifying! We'll likely get this in officially next week during the next group review.

**Comment by gkeishin** [comment]
Sure thing. Appreciated

**Comment by mraineri** [comment]
Approved 10/10

**Pull request merged**
